{% set name = "subversion" %}
{% set version = "1.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.apache.org/subversion/subversion-{{ version }}.tar.bz2
  sha256: 6ba8e218f9f97a83a799e58a3c6da1221d034b18d9d8cbbcb6ec52ab11722102

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf  # [unix]
    - libtool  # [unix]
    - pkg-config  # [unix]
    - nasm
    - make
    - python >=2.7,<3
  host:
    - boost-cpp
    - libapr
    - libaprutil
    - sqlite
    - zlib
    - openssl
    - libdb
    - lz4-c
    - libutf8proc
    - gettext
    - expat
    - gnupg  # [unix]
    - cyrus-sasl  # [unix]
    - libmagic  # [unix]
    - serf  # [linux]
    - swig
    - perl >=5.8.0
  run:
    - libapr
    - libaprutil
    - gettext
    - expat
    - perl >=5.8.0

test:
  commands:
    - svn --help
  imports:
    - SVN::Client
    - SVN::Core

about:
  home: https://subversion.apache.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Enterprise-class centralized version control for the masses
  doc_url: https://subversion.apache.org/docs/
  dev_url: https://subversion.apache.org/source-code.html

extra:
  recipe-maintainers:
    - scopatz
